
version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: nginx1
    ports:
      - "8080:8000"
    volumes:
      - ./webapp:/webapp
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/nginx:/etc/nginx/sites-available
      - ./config/nginx:/etc/nginx/sites-enabled
    depends_on:
        - web
  db:
    image: mysql:5.7
    ports:
      - '3305:3305'
    environment:
       MYSQL_DATABASE: 'my-app-db'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
  web:
     build: ./webapp
     command: bash -c "python manage.py makemigrations & python manage.py migrate & gunicorn django_environments.wsgi:application -b 0.0.0.0:8000 --workers 3"
     command: python manage.py runserver 0.0.0.0:8000 
     volumes: 
       - ./webapp:/webapp
     expose: 
       - "8000"
     depends_on:
       - db 

