# Generated by Django 2.1.7 on 2019-04-07 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('saldo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('NumeroCuentaBancaria', models.IntegerField(primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=8)),
                ('FechaInicio', models.DateField(null=True)),
                ('FechaFin', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosBancarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreServicio', models.CharField(max_length=150)),
                ('FechaInicio', models.DateField(null=True)),
                ('FechaFin', models.DateField(null=True)),
                ('NumeroCuentaBancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.CuentaBancaria')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('DebitoCredito', models.IntegerField()),
                ('Monto', models.DecimalField(decimal_places=4, max_digits=8)),
                ('Decripcion', models.CharField(max_length=150)),
                ('FechaTransaccion', models.DateField(null=True)),
                ('CuentaDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DestinoCuenta', to='inicio.CuentaBancaria')),
                ('CuentaOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrigenCuenta', to='inicio.CuentaBancaria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=150)),
                ('Nombre', models.CharField(max_length=150)),
                ('Apellido', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('Fecha_Creacion', models.DateField(null=True)),
                ('FechaFin', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='serviciosbancarios',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Usuario'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='UsuarioPropietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CuentaBancariaUsuario', to='inicio.Usuario'),
        ),
    ]
